#!/bin/sh
# tmux-split-in-cwd - open a new shell with same cwd as calling pane

if [ -n "$TMUX_PWD" ]; then
  cd $TMUX_PWD
fi

if [ -z "$TMUX_SHELL" ]; then
  TMUX_SHELL=$SHELL
fi

if [ -n "$(which reattach-to-user-namespace)" ]; then
  exec reattach-to-user-namespace -l $TMUX_SHELL
else
  exec $TMUX_SHELL
fi
