#!/bin/sh
# tmux-split-in-cwd - open a new shell with same cwd as calling pane

if [ "x$TMUX_PWD" != "x" ]; then
  cd $TMUX_PWD
fi

if [ "x$TMUX_SHELL" == "x" ]; then
  TMUX_SHELL=$SHELL
fi

if [ "x$(which reattach-to-user-namespace)" != "x" ]; then
  exec reattach-to-user-namespace -l $TMUX_SHELL
else
  exec $TMUX_SHELL
fi
