#!/bin/sh
# tmux-split-in-cwd - open a new shell with same cwd as calling pane

SIP=$(tmux display-message -p "#S:#I:#P")
PTY=$(tmux server-info |
        egrep flags=\|bytes |
        awk '/windows/ { s = $2 }
             /references/ { i = $1 }
             /bytes/ { print s i $1 $2 } ' |
        grep "$SIP" |
        cut -d: -f4)
PTS=${PTY#/dev/}
PID=$(ps -eao pid,tty | awk '$2 == "'$PTS'" {print $1; exit}')
DIR=$(lsof -a -p $PID -d cwd -Fn | awk '/^n/ {$0=substr($0,2); print}')
EXE=$(lsof -a -p $PID -d txt -Fn | awk '/^n/ {$0=substr($0,2); print; exit}')

tmux setenv TMUX_SHELL "$EXE"
tmux setenv TMUX_PWD "$DIR"

case "$1" in
  -h) tmux splitw -h "exec ~/.tmux/new-window"
     ;;
  -v) tmux splitw -v "exec ~/.tmux/new-window"
     ;;
  *) tmux neww "exec ~/.tmux/new-window"
     ;;
esac
